version: "3"
services:
  nginx:
    image: nginx:1.17.0-alpine
    container_name: nginx
    depends_on:
      - php-fpm
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    # command: cat /etc/nginx/nginx.conf
  php-fpm:
    image: php:7.2-fpm-alpine
    container_name: php-fpm
    ports:
      - 9000:9000
    volumes:
      - ./php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./index.php:/var/www/html/index.php
    # command: cat /usr/local/etc/php-fpm.d/www.conf